"""Added tag column

Revision ID: 5be53d99912b
Revises: 1918d83ceda4
Create Date: 2020-12-30 19:22:01.422485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be53d99912b'
down_revision = '1918d83ceda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('tag', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'tag')
    # ### end Alembic commands ###
